### PR TITLE
Add a log engine

### PR DESCRIPTION
**Pull request by my-kel**
Hi,

Here is a simple log system. Confidential parameters are filtered, but I will let you review my PR to check if some of them have been forgotten.

I added a section on documentation to explain how to enable/disable logs.

### CODE REVIEW

**Comment by hobailey** [comment]
Thanks very much @my-kel for all this great work - we'll take a look and get back to you :-)

**Comment by my-kel** [comment]
Hi @hobailey,

Is there anything wrong with my PR? How can I help you to merge it?

Regards.

**Comment by hobailey** [comment]
Looks good, thanks very much again for the contribution and sorry for the delay getting back to you :-)

**Comment by my-kel** [comment]
You're welcome @hobailey! No worries about the delay :smile:

**Pull request merged**
