### PR TITLE
Add Dispute

### PR DESCRIPTION
**Pull request by laurynas**

### CODE REVIEW

**Comment by hobailey** [comment]
@laurynas - had you seen our disputes branch (https://github.com/Mangopay/mangopay2-ruby-sdk/tree/disputes) with all the relevant code? We're just about to merge it into the master in the next couple of hours;

**Comment by laurynas** [comment]
Hey @hobailey! No, I haven't seen it. Good to know it will be released soon :rocket:  Closing my PR.

**Comment by hobailey** [comment]
@laurynas this has just been merged with #34 :-)

**Comment by laurynas** [comment]
@hobailey Cool! That was good timing. Waiting for new gem version :)

**Pull request closed without merging**
