### PR TITLE
Test build on multiple Ruby versions

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by nicolasleger** [comment]
I think tests are not determinist 😔since
- on my fork https://travis-ci.org/nicolasleger/mangopay2-ruby-sdk/builds/335398115 2.0.0 2.1 and 2.2 works
- but here in the same PR none https://travis-ci.org/Mangopay/mangopay2-ruby-sdk/builds/335403451

**Comment by nicolasleger** [comment]
@mickaelpois what do you think?

**Comment by mickaelpois** [comment]
@nicolasleger I'm trying to run your tests again. I've got the same issue with PHP build, which has multiple versions to test.
Running one by one every tests make them green, I don't really know why there's an issue like that (ID collision? I don't think so...)
If everything goes green, I'll merge this PR with a great pleasure 👍

**Comment by nicolasleger** [comment]
OK, would be better to find why it fails because it will rehappen multiple times again.

**Pull request merged**
