### PR TITLE
Send headers for different api calls

### PR DESCRIPTION
**Pull request by andriiNyzhnik**
Add possibility to send headers for a bunch of methods

### CODE REVIEW

**Comment by mangomaxoasis** [comment]
HI @andriiNyzhnik  
We'll need to review this
We'll keep you posted 
Max

**Comment by mangomaxoasis** [comment]
Hello @andriiNyzhnik 
We need to consider these changes in our testing process 
We'll get back to you 
Max

**Comment by SoloJr** [comment]
Hi @andriiNyzhnik 

There are some tests that are failing due to your PR. If you fix your code so that the tests pass, we'll be more than happy to accept your pull request.

**Comment by andriiNyzhnik** [comment]
@SoloJr fixed

**Pull request merged**
