### PR TITLE
Add support for refund creation

### PR DESCRIPTION
**Pull request by CrAsH1101**
Add support to create refunds for PayIn, Transfer and PayOut transactions.

PayIn example
`MangoPay::PayIn.refund(pay_in_id, { AuthorId: user_id })`

### CODE REVIEW

**Comment by CrAsH1101** [comment]
Can somebody please check why CI/CD is failing on everything?
Thank you

**Comment by fredericdelordm** [comment]
Hello @CrAsH1101,

Thank you for your PR and your time. We are going to review it as soon as possible.

Have a nice day,

**Comment by SoloJr** [comment]
Hello @CrAsH1101 

Please pull the latest from master in your branch in order to fix the build issues. Then I will gladly review your PR. 

Thanks,
SoloJr

**Comment by CrAsH1101** [comment]
Done!

**Pull request merged**
